Nguyen Anh Tuan week 7
vbee-holding/20221 pull request #44
Opened 2022-11-18 15:51 UTC by NguyenAnhTuan-20194201

Nguyen Anh Tuan week 7

2022-11-18 16:04 UTC, haitd-vbee reviewed
Mất báo cáo của bạn 20204510 rồi

2022-11-18 16:23 UTC, haitd-vbee commented on week-7/20194201/Server_SV/.env
> +DB_CONNECTION= mongodb+srv://SV:sv123456789@cluster0.vp0j8zy.mongodb.net/?retryWrites=true&w=majority
Add a new line at end of file

2022-11-18 16:23 UTC, haitd-vbee commented on week-7/20194201/Server_SV/app.js
> +});
Add a new line at end of file

2022-11-18 16:25 UTC, haitd-vbee commented on week-7/20194201/Server_SV/controllers/student.js
> +studentController.addStudent = (req, res,next) =>{
```suggestion
studentController.addStudent = (req, res, next) =>{
```

2022-11-18 16:26 UTC, haitd-vbee commented on week-7/20194201/Server_SV/models/student.js
> +module.exports = mongoose.model('student', studentSchema);
Add a new line at end of file

2022-11-18 16:27 UTC, haitd-vbee commented on week-7/20194201/Server_SV/routes/index.js
> +module.exports =  apiRoutes;
Add a new line at end of file

2022-11-18 16:37 UTC, haitd-vbee commented on week-7/20194201/Server_SV/routes/index.js
> +const experess = require("express");
```suggestion
const express = require("express");
```

2022-11-18 17:12 UTC, haitd-vbee approved these changes

2022-11-19 06:18 UTC, thanhnx-vbee requested changes

2022-11-19 06:18 UTC, thanhnx-vbee commented on .gitignore
> +
add `.env `and `upload` in gitignore

2022-11-19 08:26 UTC, thanhnx-vbee requested changes

2022-11-19 08:26 UTC, thanhnx-vbee commented on week-7/20194201/Server_SV/env
> +DB_CONNECTION = " "
DB_CONNECTION=

2022-11-19 08:35 UTC, thanhnx-vbee approved these changes

2022-11-19 08:35 UTC, merged