add week7 folder
vbee-holding/20221 pull request #45
Opened 2022-11-18 17:57 UTC by BuiThucNam

add week7 folder

2022-11-18 17:59 UTC, haitd-vbee submitted a review, later dismissed

2022-11-19 06:21 UTC, thanhnx-vbee requested changes

2022-11-19 06:21 UTC, thanhnx-vbee commented on week-7/20200857/StudentAPI/src/config/db/connect.js
> +        await mongoose.connect('mongodb://localhost:27017/Student_API', {
Tạo file .env và lưu biến  `mongodb://localhost:27017/Student_API`

2022-11-19 12:15 UTC, haitd-vbee approved these changes

2022-11-19 15:21 UTC, thanhnx-vbee approved these changes

2022-11-19 15:21 UTC, merged